import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Function to render menu items
const menuItems = () => (
  <>
    <li>
      <Link href="/">Home</Link>
    </li>
    <li>
      <Link href="/Feature">Feature</Link>
    </li>
    <li>
      <Link href="/how-it-works">How It Works</Link>
    </li>
    <li>
      <Link href="/testimonial">Testimonial</Link>
    </li>
  </>
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <div className="navbar bg-base-100 shadow-sm">
            <div className="navbar-start">
              <div className="dropdown">
                <div
                  tabIndex={0}
                  role="button"
                  className="btn btn-ghost lg:hidden"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h8m-8 6h16"
                    />
                  </svg>
                </div>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow"
                >
                  {menuItems()}
                </ul>
              </div>
              <a className="btn btn-ghost text-xl">IHSS</a>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal px-1">{menuItems()}</ul>
            </div>
            <div className="navbar-end">
              <div className="hidden lg:flex gap-3">
                <Link href="/login">
                  <button className="btn btn-primary">Login</button>
                </Link>
                <Link href="/register">
                  <button className="btn btn-secondary">Register</button>
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {/* Main Content */}
        {children}

        {/* Footer */}
        <footer className="bg-base-200 text-center py-5 mt-10">
          <div className="container mx-auto">
            <p className="text-sm">
              © {new Date().getFullYear()} IHSS. All rights reserved.
            </p>
            <div className="flex justify-center gap-4 mt-3">
              <Link href="/privacy-policy" className="link link-hover">
                Privacy Policy
              </Link>
              <Link href="/terms-of-service" className="link link-hover">
                Terms of Service
              </Link>
              <Link href="/contact-us" className="link link-hover">
                Contact Us
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}